### ISSUE TITLE
No primary alignment for some reads

### ISSUE THREAD

**Issue by amwenger** [philres/ngmlr#11]
According to the [SAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf):

> For each read/contig in a SAM file, it is required that one and only one line associated with the read satisfies 'FLAG & 0x900 == 0'.  This line is called the primary line of the read.

For certain inputs ([test case](https://gist.github.com/amwenger/56f2921ae796cfcd82483da66445b544)), `NGM-LR` produces no primary alignments.  It does seem to be reference-specific, as modifying the reference from the test case to have only a single contig will produce a primary alignment.

**Comment by philres** [comment]
Thanks for the test case! I'll have a look at it and get back to you as soon as possible!

**Comment by philres** [comment]
Hi! The new ngmlr version is available and should fix the problems with the missing primary alignments!

Would appreciate it if you could let me know if the new version works for you data-set.

Thanks,
Philipp

**Comment by amwenger** [comment]
The fix does resolve the issue for the test case that I submitted, and also works for larger datasets.

Thank you, @philres.

**Comment by philres** [comment]
Happy to hear that, thanks for letting me know!
