### ISSUE TITLE
NGMLR may produce non-deterministic MAPQ from run to run

### ISSUE THREAD

**Issue by ylipacbio** [philres/ngmlr#13]
Hi Philip,

We observed that NGMLR may produce non-deterministic MAPQ from run to run on a tiny test case. Would you please take a look? Thanks!

query fasta
https://www.dropbox.com/s/9q6cuiee4s8qr57/query.fasta?dl=0

reference fasta
https://www.dropbox.com/s/dm0iytvvq3o5dwy/reference.fasta?dl=0

command:
`cat query.fasta | ngmlr -x pacbio --no-progress -t 4 -R 0.01 -r reference.fasta -q /dev/stdin -o out.bam`

Running the above command 10 times gives me alignments with different MAPQ values.

Thank you!

**Comment by philres** [comment]
Thank you! I'll take a look at it!

**Comment by philres** [comment]
Hi! The new ngmlr version is available now and contains a fix for the non deterministic MAPQ values. Would be great if you could checke whether everything works now as expected for your data-sets.

Thanks,
Philipp

**Comment by ylipacbio** [comment]
Thank you very much for fixing this issue! Can not wait to try the new version!

On Mar 30, 2017 6:28 AM, Philipp Rescheneder <notifications@github.com> wrote:

Hi! The new ngmlr version is available now and contains a fix for the non deterministic MAPQ values. Would be great if you could checke whether everything works now as expected for your data-sets.

Thanks,
Philipp
