### ISSUE TITLE
Documentation of custom SAM tags

### ISSUE THREAD

**Issue by williamrowell** [philres/ngmlr#15]
I'm sorry if this already exists and I just haven't found it, but do you have any documentation of the custom SAM tags produced by ngmlr?

Thanks!

**Comment by fritzsedlazeck** [comment]
Not yet, some are explained for our short read mapper:
https://github.com/Cibiv/NextGenMap/wiki/Documentation#custom-sam-tags

**Comment by williamrowell** [comment]
Thanks! I found that page earlier and determined XI, XS (I guessed this was XE in the short read mapper), and XR.  I was trying to find out what SV, CV, ID, KB, and SB were, specifically.  If QE and QS aren't the same as the tags in PacBio BAMs, I wanted to know what those were as well.

**Comment by philres** [comment]
Most of the extra tags are manly used for debuging and testing purposes:

SV: A special tag we use to pass along information from ngmlr to sniffles
CV: Tells you how many of the read bp were aligned in this alignment (in %). For example if a read is 5000 long and the alignment contains 4000 of those bp, CV should be 80
ID: The internal ID ngmlr assigned to the read
KB: average number of k-mer hits per 100 bp for the read
SB: average per 100 bp for this read (alignment_score / read_length * 100)

QE and QS are conceptually the same as in the PacBio BAMs. QS tells you at what position of the read the alignment starts and QE at what position of the read the alignment ends. However, this information comes only from our alignment, so wie do not carry over any information contained in the PacBio BAM or h5 files or FASTQ headers.

With one of the next releases I will most probably remove several of these flags as they are not really helpful for downstream analysis.

If you would like to see any additional flag, please let us know!

**Comment by williamrowell** [comment]
Thanks @philres !  That was very helpful.
