### ISSUE TITLE
Misses first 8kb of file when reading from /dev/stdin

### ISSUE THREAD

**Issue by amwenger** [philres/ngmlr#16]
NGM-LR v0.2.3 seems to be skipping the first about 8 kilobytes of an input FASTA file when the input is provided from /dev/stdin or another Unix device.

For [test.fa](https://gist.github.com/amwenger/f2e879b935bbf929dc6fc7155cf7c9dd), a sample file with 5 reads:

    # 5/5 reads map when the file is provided by filename
    > ngmlr -r hg38.fa -q test.fa 2>&1 | grep Done
    Done (5 reads mapped (100.00%), 0 reads not mapped, 5 lines written)(elapsed: 0m, 0 r/s)

    # no reads are identified when the file is provided from /dev/stdin
    > cat test.fa | ngmlr -r hg38.fa -q /dev/stdin 2>&1 | grep Done
    Done (0 reads mapped (0.00%), 0 reads not mapped, 0 lines written)(elapsed: 0m, 0 r/s)

Once an initial buffer is cleared, the reads start to map (skips first 8 reads here):

    # 2/10 reads map when the file is concatenated with itself
    > cat test.fa test.fa | ngmlr -r hg38.fa -q /dev/stdin 2>&1 | grep Done
    Done (2 reads mapped (100.00%), 0 reads not mapped, 2 lines written)(elapsed: 0m, 0 r/s)
    
    #7/15 reads map when the file is concatenated with itself twice
    > cat test.fa test.fa test.fa | ngmlr -r hg38.fa -q /dev/stdin 2>&1 | grep Done
    Done (7 reads mapped (100.00%), 0 reads not mapped, 7 lines written)(elapsed: 0m, 0 r/s)

**Comment by philres** [comment]
Hi and thanks for the bug report!

The reason for this behaviour was that ngmlr read the first few thousand bytes to check/determine the format for the input file, closed the file and opened it again to start from the beginning. This works fine with regular files but obviously not with stdin.

I removed the format check as it is not strictly necessary as long as we only support FASTA/Q as input.

I pushed the changes to the master branch on github. Would be great if you could verify that it works for you as well now.

With the next release I'll let ngmlr read from stdin automatically when skipping the -q parameter.

**Comment by amwenger** [comment]
Confirmed that the problem is corrected for me in **v0.2.4-dev**.

Thank you, Philipp.

**Comment by philres** [comment]
Great! 

Thanks again!

**Comment by ylipacbio** [comment]
Hi Phillip, Thanks for the quick fix! 

Our deployment team would like to upgrade to use the latest code, and I am wondering if you would make a release containing this fix? 

Thanks!

**Comment by philres** [comment]
Yes sure. Let me just finish a few more test runs over night and I'll try getting the new version out tomorrow.

**Comment by ylipacbio** [comment]
Hi Philip,

We are going to upgrade NGM-LR in our build to include the fix to this issue. I am wondering if you plan to release NGMLR v0.2.4 before this coming Friday, May 19 2017? Then, we will make upgrade plans according to your decisions.

Thank you very much!

Sincerely,
Yuan

**Comment by philres** [comment]
Hi Yuan,

Sorry for the delay, there was one last issue I had to resolve. 
Version 0.2.4 is now online. Thanks again for the feedback!

Philipp
