### ISSUE TITLE
Segmentation fault on PacBio Data

### ISSUE THREAD

**Issue by chad388** [philres/ngmlr#17]
Hi Philipp,

I am encountering a segmentation fault when using ngmlr-0.2.3 to align a set of human pacbio data to GRCh38. The alignment runs for approximately 13 hours before encountering the segmentation fault and core dump error below. I am using approximately 70x of raw pacbio subreads fastq as input into the aligner. I also attached the complete stderr file output from this job:

7fff1e569000-7fff1e58c000 rw-p 00000000 00:00 0                          [stack]
7fff1e5ff000-7fff1e600000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
/opt/lsf9/spool/1492107700.330244: line 8: 14573 Aborted                 (core dumped) /gscmnt/gc3001/assembly/Downloads/ngmlr-0.2.3/ngmlr -r /gscmnt/gc2745/graveslab/Sniffles_SV_Analysis_Yoruban_Gambian_Luhya_Aligned_to_GRCh38/HG02818_Gambian/Homo_sapiens.GRCh38.dna_sm.primary_assembly_NO_X.fasta -q /gscmnt/gc2745/graveslab/Sniffles_SV_Analysis_Yoruban_Gambian_Luhya_Aligned_to_GRCh38/HG02818_Gambian/filtered_subreads_70x.fastq -o Gambian_70x_raw_pacbio_aligned_GRCh38_NGMLR.sam -t 24

Below is the alignment command that was used. So far, I have only encountered this issue with this particular dataset. I have had another alignment running now for approximately 26 hours using the same amount of data from a different sample and so far have noticed no issues with that alignment job:

/gscmnt/gc3001/assembly/Downloads/ngmlr-0.2.3/ngmlr -r /gscmnt/gc2745/graveslab/Sniffles_SV_Analysis_Yoruban_Gambian_Luhya_Aligned_to_GRCh38/HG02818_Gambian/Homo_sapiens.GRCh38.dna_sm.primary_assembly_NO_X.fasta -q /gscmnt/gc2745/graveslab/Sniffles_SV_Analysis_Yoruban_Gambian_Luhya_Aligned_to_GRCh38/HG02818_Gambian/filtered_subreads_70x.fastq -o Gambian_70x_raw_pacbio_aligned_GRCh38_NGMLR.sam -t 24

Best,
Chad
[gambian_ngmlr_alignment.err.tar.gz](https://github.com/philres/ngmlr/files/965535/gambian_ngmlr_alignment.err.tar.gz)

**Comment by philres** [comment]
Hi Chad,

thanks for your message. I have been working on a new version (0.2.4-dev) that addresses several issues related so segmentation faults in ngmlr.

It would be great if you could run it with your data to check whether it resolves the problem. You could either pull it from the github master branch and compile it yourself or use the binary i attached to this post.

Thanks,
Philipp

[ngmlr-0.2.4-dev-beta-linux-x86_64.tar.gz](https://github.com/philres/ngmlr/files/990649/ngmlr-0.2.4-dev-beta-linux-x86_64.tar.gz)

**Comment by chad388** [comment]
Hi Philipp,

Thank you for providing the test version. I will launch the alignment on my data now and let you know whether it resolves the issue. Thanks again for your help with this.

Best,
Chad

**Comment by philres** [comment]
Great, thank you!
