### ISSUE TITLE
Explaination of SV Tag?

### ISSUE THREAD

**Issue by dantaki** [philres/ngmlr#18]
The documentation for the SV tag is sparse. I noticed it's used for Sniffles, but I was wondering if I could have some more information about this tag, for example what does the signed integer following the tag indicate?

Is it the number of Supplementary Alignments for a given read? Thanks for the response.

**Comment by philres** [comment]
Hi!

The SV tag is a bit flag we use for communication between ngmlr and sniffle. The first bit is set if a read was clipped because of Ns in the reference sequence.

Please, let me know if you need any additional tags.

Thanks,
Philipp
