### ISSUE TITLE
precompiled version of latest ngmlr for linux

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [philres/ngmlr#19]
Hi Philip,
We would like to take your latest version from ngmlr for a spin at a MinION workshop we are holding in Oz. Unfortunately there are some issues with the compilation on our HP cluster. Any chance you can get a precompiled version of ngmlr up as well.

Thanks!
Benjamin

**Comment by philres** [comment]
Hi Benjamin,

Sorry, I just realised, that I forgot to update the link in the README. 
Here you go: https://github.com/philres/ngmlr/releases/download/v0.2.4/ngmlr-0.2.4-beta-linux-x86_64.tar.gz

Please let me now in case it doesn't work for you.

Best,
Philipp
