### ISSUE TITLE
Core dump on Ubuntu 16.04

### ISSUE THREAD

**Issue by colindaven** [philres/ngmlr#20]
Hi,

I am getting a core dump on a bioconda compiled recent version 0.2.4.
ngmlr 0.2.4 (build: May 18 2017 12:08:24, start: 2017-05-23.15:39:20)

Can't share the data because of data protection issues, sorry. These are certainly not long reads, about 3kbp N50. Aligning with 20 cores vs hg19.

<code>
7f9f3b800000-7f9f3c000000 rw-p 00000000 00:00 0
7f9f3c000000-7f9f3c9ae000 rw-p 00000000 00:00 0
7f9f3c9ae000-7f9f40000000 ---p 00000000 00:00 0
7f9f40094000-7f9f40095000 ---p 00000000 00:00 0
7f9f40095000-7f9f40895000 rw-p 00000000 00:00 0
7f9f40895000-7f9f40896000 ---p 00000000 00:00 0
7f9f40896000-7f9f41096000 rw-p 00000000 00:00 0
7f9f41096000-7f9f41097000 ---p 00000000 00:00 0
7f9f41097000-7f9f41897000 rw-p 00000000 00:00 0
7f9f41897000-7f9f41898000 ---p 00000000 00:00 0
7f9f41898000-7fa07c92e000 rw-p 00000000 00:00 0
7fa07c92e000-7fa07caed000 r-xp 00000000 08:02 5384958                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa07caed000-7fa07cced000 ---p 001bf000 08:02 5384958                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa07cced000-7fa07ccf1000 r--p 001bf000 08:02 5384958                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa07ccf1000-7fa07ccf3000 rw-p 001c3000 08:02 5384958                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa07ccf3000-7fa07ccf7000 rw-p 00000000 00:00 0
7fa07ccf7000-7fa07cd0d000 r-xp 00000000 00:2a 2450403566                 /mnt/ngsnfs/tools/miniconda2/lib/libgcc_s.so.1
7fa07cd0d000-7fa07cf0c000 ---p 00016000 00:2a 2450403566                 /mnt/ngsnfs/tools/miniconda2/lib/libgcc_s.so.1
7fa07cf0c000-7fa07cf0d000 rw-p 00015000 00:2a 2450403566                 /mnt/ngsnfs/tools/miniconda2/lib/libgcc_s.so.1
7fa07cf0d000-7fa07cf0e000 rw-p 00074000 00:2a 2450403566                 /mnt/ngsnfs/tools/miniconda2/lib/libgcc_s.so.1
7fa07cf0e000-7fa07d016000 r-xp 00000000 08:02 5384950                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa07d016000-7fa07d215000 ---p 00108000 08:02 5384950                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa07d215000-7fa07d216000 r--p 00107000 08:02 5384950                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa07d216000-7fa07d217000 rw-p 00108000 08:02 5384950                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa07d217000-7fa07d382000 r-xp 00000000 00:2a 2450392931                 /mnt/ngsnfs/tools/miniconda2/lib/libstdc++.so.6.0.21
7fa07d382000-7fa07d582000 ---p 0016b000 00:2a 2450392931                 /mnt/ngsnfs/tools/miniconda2/lib/libstdc++.so.6.0.21
7fa07d582000-7fa07d58c000 r--p 0016b000 00:2a 2450392931                 /mnt/ngsnfs/tools/miniconda2/lib/libstdc++.so.6.0.21
7fa07d58c000-7fa07d58e000 rw-p 00175000 00:2a 2450392931                 /mnt/ngsnfs/tools/miniconda2/lib/libstdc++.so.6.0.21
7fa07d58e000-7fa07d592000 rw-p 00000000 00:00 0
7fa07d592000-7fa07d5d3000 rw-p 00178000 00:2a 2450392931                 /mnt/ngsnfs/tools/miniconda2/lib/libstdc++.so.6.0.21
7fa07d5d3000-7fa07d5eb000 r-xp 00000000 08:02 5385490                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa07d5eb000-7fa07d7ea000 ---p 00018000 08:02 5385490                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa07d7ea000-7fa07d7eb000 r--p 00017000 08:02 5385490                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa07d7eb000-7fa07d7ec000 rw-p 00018000 08:02 5385490                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa07d7ec000-7fa07d7f0000 rw-p 00000000 00:00 0
7fa07d7f0000-7fa07d806000 r-xp 00000000 00:2a 2450422365                 /mnt/ngsnfs/tools/miniconda2/lib/libz.so.1.2.8
7fa07d806000-7fa07da05000 ---p 00016000 00:2a 2450422365                 /mnt/ngsnfs/tools/miniconda2/lib/libz.so.1.2.8
7fa07da05000-7fa07da06000 rw-p 00015000 00:2a 2450422365                 /mnt/ngsnfs/tools/miniconda2/lib/libz.so.1.2.8
7fa07da06000-7fa07da2c000 r-xp 00000000 08:02 5384962                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa07dc09000-7fa07dc0e000 rw-p 00000000 00:00 0
7fa07dc28000-7fa07dc2b000 rw-p 00000000 00:00 0
7fa07dc2b000-7fa07dc2c000 r--p 00025000 08:02 5384962                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa07dc2c000-7fa07dc2d000 rw-p 00026000 08:02 5384962                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa07dc2d000-7fa07dc2e000 rw-p 00000000 00:00 0
7fff35142000-7fff35164000 rw-p 00000000 00:00 0                          [stack]
7fff3517f000-7fff35181000 r--p 00000000 00:00 0                          [vvar]
7fff35181000-7fff35183000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

[1]+  Aborted                 (core dumped) ngmlr -t 20 -r /lager2/rcug/seqres/HS/bwa/hg19.fa -q ../BRCA2_dup_allreads.fastq -o BRCA2_dup_allreads_ngmlr.sam -x ont
</code>

**Comment by colindaven** [comment]
This also happens when just rerunning the same command on one thread (just tested).

**Comment by fritzsedlazeck** [comment]
Could you send us the complete log for that run?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Thanks for posting that. could you also show me the last few lines from out1.log ?
Thanks
Fritz

**Comment by philres** [comment]
Hi,

sorry for the delay. We have implemented a potential fix for this problem. Would be great if you could try this ( [ngmlr-0.2.5-dev-beta-linux-x86_64.tar.gz](https://github.com/philres/ngmlr/files/1084791/ngmlr-0.2.5-dev-beta-linux-x86_64.tar.gz) ) version of ngmlr on your data. If you prefer you can als compile it yourself. I pushed the changes to the master branch.

Thanks,
Philipp

**Comment by colindaven** [comment]
Hi Philipp,

great, thanks. This fix resolved the issue on ont data. I did not recompile, but used your binary version.

Best wishes,
Colin

**Comment by philres** [comment]
Great! Thanks for letting me know!

2017-06-20 10:55 GMT+02:00 Colin Davenport <notifications@github.com>:
