### ISSUE TITLE
install problem on Fedora 25

### ISSUE THREAD

**Issue by jblamyatifremer** [philres/ngmlr#21]
Dear ngmlr creator,

I am on fedora 25, 8 cores, 32 Gb of Ram.
I also checked that all needed libraries have been installed namely (git wget gcc g++ libc6-dev make cmake zlib1g-dev) and checked in gcc > 4.9... But i failed to compile the ngmlr. I am sure that i have some dependency problems, but i can not found which library is missing.

During the install process : 
/usr/bin/ld : ne peut trouver [ENGLISH TRADUCTION : can't found] -lz
/usr/bin/ld : ne peut trouver [ENGLISH TRADUCTION : can't found] -lpthread
/usr/bin/ld : ne peut trouver [ENGLISH TRADUCTION : can't found] -lstdc++
/usr/bin/ld : ne peut trouver [ENGLISH TRADUCTION : can't found] -lm
/usr/bin/ld : ne peut trouver [ENGLISH TRADUCTION : can't found] -lc
collect2: erreur : ld a retourné 1 code d'état d'exécution  [ENGLISH TRADUCTION :collect2: error: ld exit with error code : 1 ]

Below, I copy/paste the whole output : 

[userlocal@lt-231 build]$ make
[  0%] Built target recompile_always
Scanning dependencies of target ngmlr
[  3%] Building CXX object src/CMakeFiles/ngmlr.dir/AlignmentMatrix.cpp.o
[  7%] Building CXX object src/CMakeFiles/ngmlr.dir/AlignmentMatrixFast.cpp.o
[ 11%] Building CXX object src/CMakeFiles/ngmlr.dir/ArgParser.cpp.o
[ 15%] Building CXX object src/CMakeFiles/ngmlr.dir/CS.cpp.o
[ 19%] Building CXX object src/CMakeFiles/ngmlr.dir/CSstatic.cpp.o
[ 23%] Building CXX object src/CMakeFiles/ngmlr.dir/ConvexAlign.cpp.o
[ 26%] Building CXX object src/CMakeFiles/ngmlr.dir/ConvexAlignFast.cpp.o
[ 30%] Building CXX object src/CMakeFiles/ngmlr.dir/LinearRegression.cpp.o
[ 34%] Building CXX object src/CMakeFiles/ngmlr.dir/Logging.cpp.o
[ 38%] Building CXX object src/CMakeFiles/ngmlr.dir/MappedRead.cpp.o
[ 42%] Building CXX object src/CMakeFiles/ngmlr.dir/main.cpp.o
[ 46%] Building CXX object src/CMakeFiles/ngmlr.dir/NGM.cpp.o
[ 50%] Building CXX object src/CMakeFiles/ngmlr.dir/NGMTask.cpp.o
[ 53%] Building CXX object src/CMakeFiles/ngmlr.dir/AlignmentBuffer.cpp.o
[ 57%] Building CXX object src/CMakeFiles/ngmlr.dir/PrefixTable.cpp.o
[ 61%] Building CXX object src/CMakeFiles/ngmlr.dir/ReadProvider.cpp.o
[ 65%] Building CXX object src/CMakeFiles/ngmlr.dir/SamParser.cpp.o
[ 69%] Building CXX object src/CMakeFiles/ngmlr.dir/SAMWriter.cpp.o
[ 73%] Building CXX object src/CMakeFiles/ngmlr.dir/SequenceProvider.cpp.o
[ 76%] Building CXX object src/CMakeFiles/ngmlr.dir/OutputReadBuffer.cpp.o
/home/userlocal/ngmlr/src/OutputReadBuffer.cpp: Dans le destructeur « OutputReadBuffer::~OutputReadBuffer() »:
/home/userlocal/ngmlr/src/OutputReadBuffer.cpp:17:9: attention : throw will always call terminate() [-Wterminate]
   throw "Elements left in buffer!";
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/userlocal/ngmlr/src/OutputReadBuffer.cpp:17:9: note : in C++11 destructors default to noexcept
[ 80%] Building CXX object src/CMakeFiles/ngmlr.dir/ScoreBuffer.cpp.o
[ 84%] Building CXX object src/CMakeFiles/ngmlr.dir/StrippedSW.cpp.o
[ 88%] Building C object src/CMakeFiles/ngmlr.dir/__/lib/Complete-Striped-Smith-Waterman-Library/src/ssw.c.o
[ 92%] Building CXX object src/CMakeFiles/ngmlr.dir/unix.cpp.o
[ 96%] Building CXX object src/CMakeFiles/ngmlr.dir/unix_threads.cpp.o
[100%] Linking CXX executable ../../bin/ngmlr-0.2.5-dev/ngmlr
/usr/bin/ld : ne peut trouver -lz
/usr/bin/ld : ne peut trouver -lpthread
/usr/bin/ld : ne peut trouver -lstdc++
/usr/bin/ld : ne peut trouver -lm
/usr/bin/ld : ne peut trouver -lc
collect2: erreur : ld a retourné 1 code d'état d'exécution
src/CMakeFiles/ngmlr.dir/build.make:719 : la recette pour la cible « ../bin/ngmlr-0.2.5-dev/ngmlr » a échouée
make[2]: *** [../bin/ngmlr-0.2.5-dev/ngmlr] Erreur 1
CMakeFiles/Makefile2:124 : la recette pour la cible « src/CMakeFiles/ngmlr.dir/all » a échouée
make[1]: *** [src/CMakeFiles/ngmlr.dir/all] Erreur 2
Makefile:129 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

JB

**Comment by philres** [comment]
Hi JB,

could you please download this already compiled binary and check whether it works for you?

https://github.com/philres/ngmlr/files/1084791/ngmlr-0.2.5-dev-beta-linux-x86_64.tar.gz

Thanks,
Philipp

**Comment by jblamyatifremer** [comment]
It works perfectly... 

I feel a bit idiot, since your README starts with "Download binary from github and unzip"
I  make my apologies.

A last question : It seems that ngmlr create a reference index on the fly (i do not find an equivalent of bwa index) ?  

You could close this thread. 
Thanks
JB

**Comment by philres** [comment]
Great happy to hear that!

Yes NGMLR creates an index consisting of the two following files:

<reference name>-ht-13-2.2.ngm
<reference name>-enc.2.ngm

Everything is done automatically, if the index does not exists NGMLR
creates it. No need to build it manually.



2017-06-20 17:55 GMT+02:00 jblamyatifremer <notifications@github.com>:
