### ISSUE TITLE
"Could not determine chromosome for interval." error

### ISSUE THREAD

**Issue by skoren** [philres/ngmlr#23]
I am mapping some human nanopore reads (http://s3.amazonaws.com/nanopore-human-wgs/rel3-nanopore-wgs-288418386-FAB39088.fastq.gz) and am getting the above error. I am mapping to only the primary chromosomes/contigs from GRCh38 which I've posted here: https://gembox.cbcb.umd.edu/shared/hg38.primary.fna. The full output is:
```
ngmlr 0.2.5 (build: Jun 26 2017 16:59:55, start: 2017-06-28.14:40:31)
Contact: philipp.rescheneder@univie.ac.at
Wrinting output (SAM) to stdout
Encoding reference sequence.
Size of reference genome 3098 Mbp (max. 68719 Mbp)
Allocating 1549494220 (3150443136) bytes for the reference.
BinRef length: 1549494124ll (elapsed 14.166944)
0 reference sequences were skipped (length < 10).
Writing encoded reference to hg38.primary.fna-enc.2.ngm
Writing to disk took 4.40s
Building reference table
Allocated 1 hashtable units (tableLocMax=2^32.000000, genomeSize=2^31.529150)
Building RefTable #0 (kmer length: 13, reference skip: 2)
	Number of k-mers: 67108865
	Counting kmers took 67.92s
	Average number of positions per prefix: 15.640394
	66299 prefixes are ignored due to the frequency cutoff (1000)
	Index size: 335544325 byte (67108865 x 5)
	Generating index took 3.45s
	Allocating and initializing prefix Table took 1.25s
	Number of prefix positions is 860690554 (4)
	Size of RefTable is 3442762216
	Number of repetitive k-mers ignored: 368691
	Overall time for creating RefTable: 338.32s
Writing RefTable to hg38.primary.fna-ht-13-2.2.ngm
Writing to disk took 10.57s
Mapping reads...
Could not determine chromosome for interval.
Terminating
```

The majority of the data seems to be running without error. Thanks for any help.

**Comment by philres** [comment]
Hi Skoren,

thanks for reporting this. I was able to reproduce the problem when mapping to hg38.primary.fna

I'll try to fix it today or tomorrow.

Thanks,
Philipp

**Comment by philres** [comment]
Hi again,

just a quick update. I could fix the problem and will upload the new version as soon as tests are finished. This might take till tomorrow.

Philipp

**Comment by fritzsedlazeck** [comment]
Hey Sergey,
the issue was indeed solved. I also had like 3 data sets that are now working. Let us know if you have other comments/suggestions.
Thanks
Fritz
