### ISSUE TITLE
Error correction of PacBio reads

### ISSUE THREAD

**Issue by Asutu** [philres/ngmlr#27]
Planning on trying NGM-LR to identify structural variations by read mapping PacBio reads to a reference genome, is it advisable to error correct PacBio reads before alignment or is just better to feed the raw data and let NGM-LR do its work? Could not see any info about this in the docs nor posters.

Thanks,
Pedro

**Comment by fritzsedlazeck** [comment]
Hi Pedro,
we are typically using raw Pacbio reads. 
Cheers
Fritz
