### ISSUE TITLE
CIGAR/MD buffer not long enough

### ISSUE THREAD

**Issue by dkainer** [philres/ngmlr#28]
I encountered the following error with some Nanopore long read data, using ngmlr v0.2.4:

CIGAR/MD buffer not long enough. Please report this!
[A[2KWarning: could not compute alignment for read 1cd31c83-45ed-4959-bba6-a65728b2209c
*** Error in `ngmlr': free(): invalid next size (fast): 0x00007efcbc207080 ***
======= Backtrace: =========
[0x528f91]
[0x531006]
[0x534a27]
[0x427a51]
[0x41fd23]
[0x41fecc]
[0x423bb0]
[0x4275f7]
[0x434990]
[0x434aa9]
[0x414f4b]
[0x41509b]
[0x415b6d]
[0x41cead]
[0x41bd19]
[0x44b825]
[0x57c469]
======= Memory map: ========
00400000-00659000 r-xp 00000000 203:acf3a 156035415797705592             /short/xf1/src_big/ngmlr-0.2.4/ngmlr
00859000-00863000 rw-p 00259000 203:acf3a 156035415797705592             /short/xf1/src_big/ngmlr-0.2.4/ngmlr
00863000-0086d000 rw-p 00000000 00:00 0 
0148a000-018c8000 rw-p 00000000 00:00 0                                  [heap]
7efb31161000-7efbb0000000 rw-p 00000000 00:00 0 
7efbb0000000-7efbb1926000 rw-p 00000000 00:00 0 
7efbb1926000-7efbb4000000 ---p 00000000 00:00 0 
7efbb43ab000-7efbd0000000 rw-p 00000000 00:00 0 
7efbd0000000-7efbd2166000 rw-p 00000000 00:00 0 
7efbd2166000-7efbd4000000 ---p 00000000 00:00 0 
7efbd5f20000-7efbe5f21000 rw-p 00000000 00:00 0 
7efbf609f000-7efc10000000 rw-p 00000000 00:00 0 
7efc10000000-7efc1194b000 rw-p 00000000 00:00 0 
7efc1194b000-7efc14000000 ---p 00000000 00:00 0 
7efc15f23000-7efc2c000000 rw-p 00000000 00:00 0 
7efc2c000000-7efc2cd01000 rw-p 00000000 00:00 0 
7efc2cd01000-7efc30000000 ---p 00000000 00:00 0 
7efc31f21000-7efc5c000000 rw-p 00000000 00:00 0 
7efc5c000000-7efc5d4a0000 rw-p 00000000 00:00 0 
7efc5d4a0000-7efc60000000 ---p 00000000 00:00 0 
7efc61f21000-7efc75f23000 rw-p 00000000 00:00 0 
7efc860a1000-7efc8c000000 rw-p 00000000 00:00 0 
7efc8c000000-7efc8ce7c000 rw-p 00000000 00:00 0 
7efc8ce7c000-7efc90000000 ---p 00000000 00:00 0 
7efc91f21000-7efcbc000000 rw-p 00000000 00:00 0 
7efcbc000000-7efcbd54d000 rw-p 00000000 00:00 0 
7efcbd54d000-7efcc0000000 ---p 00000000 00:00 0 
7efcc1f21000-7efcec000000 rw-p 00000000 00:00 0 
7efcec000000-7efced020000 rw-p 00000000 00:00 0 
7efced020000-7efcf0000000 ---p 00000000 00:00 0 
7efcf1f1f000-7efd30000000 rw-p 00000000 00:00 0 
7efd30000000-7efd30d6d000 rw-p 00000000 00:00 0 
7efd30d6d000-7efd34000000 ---p 00000000 00:00 0 
7efd37e44000-7efd51f22000 rw-p 00000000 00:00 0 
7efd54000000-7efd56428000 rw-p 00000000 00:00 0 
7efd56428000-7efd58000000 ---p 00000000 00:00 0 
7efd59f22000-7efd80000000 rw-p 00000000 00:00 0 
7efd80000000-7efd81732000 rw-p 00000000 00:00 0 
7efd81732000-7efd84000000 ---p 00000000 00:00 0 
7efd85f17000-7efd99f19000 rw-p 00000000 00:00 0 
7efd99f19000-7efd99f1a000 ---p 00000000 00:00 0 
7efd99f1a000-7efd9df1a000 rw-p 00000000 00:00 0                          [stack:26273]
7efd9df1a000-7efd9df1b000 ---p 00000000 00:00 0 
7efd9df1b000-7efda1f1b000 rw-p 00000000 00:00 0                          [stack:26272]
7efda1f1b000-7efda1f1c000 ---p 00000000 00:00 0 
7efda1f1c000-7efda5f1c000 rw-p 00000000 00:00 0                          [stack:26271]
7efda5f1c000-7efda5f1d000 ---p 00000000 00:00 0 
7efda5f1d000-7efda9f1d000 rw-p 00000000 00:00 0                          [stack:26270]
7efda9f1d000-7efda9f1e000 ---p 00000000 00:00 0 
7efda9f1e000-7efdadf1e000 rw-p 00000000 00:00 0                          [stack:26269]
7efdadf1e000-7efdadf1f000 ---p 00000000 00:00 0 
7efdadf1f000-7efdc209d000 rw-p 00000000 00:00 0                          [stack:26268]
7efdc209d000-7efdc209e000 ---p 00000000 00:00 0 
7efdc209e000-7efdc609e000 rw-p 00000000 00:00 0                          [stack:26267]
7efdc609e000-7efdc609f000 ---p 00000000 00:00 0 
7efdc609f000-7efdcfffe000 rw-p 00000000 00:00 0                          [stack:26266]
7efdcfffe000-7efdcffff000 ---p 00000000 00:00 0 
7efdcffff000-7efdd3fff000 rw-p 00000000 00:00 0                          [stack:26265]
7efdd3fff000-7efdd4000000 ---p 00000000 00:00 0 
7efdd4000000-7efdd8000000 rw-p 00000000 00:00 0                          [stack:26264]
7efdd8000000-7efdd9246000 rw-p 00000000 00:00 0 
7efdd9246000-7efddc000000 ---p 00000000 00:00 0 
7efddfe6a000-7efddfe6b000 rw-p 00000000 00:00 0 
7efddfe6b000-7efddfe6c000 ---p 00000000 00:00 0 
7efddfe6c000-7efde3e6c000 rw-p 00000000 00:00 0                          [stack:26263]
7efde3e6c000-7efde3e6d000 ---p 00000000 00:00 0 
7efde3e6d000-7efe3b739000 rw-p 00000000 00:00 0                          [stack:26262]
7fff8bda0000-7fff8bec2000 rw-p 00000000 00:00 0                          [stack]
7fff8bff7000-7fff8bff9000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by fritzsedlazeck** [comment]
Hi David,
thanks for reporting this. Its a known bug that we encountered also from others and our own experience. Would you mind updating NGMLR to 2.6 ( current release) and give it another try?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi David,
did you had a chance to test the newer version? If it works we can close this issue.
Thanks
Fritz
