### ISSUE TITLE
SEGV on nanopore real data

### ISSUE THREAD

**Issue by MuraseTomohiro** [philres/ngmlr#3]
I found the software segfaulted when mapping nanopore real data (obtained from the link below, R9 1D Rapid FASTA files, 1.5Gb) on NC_000913.3 reference sequence resulted in SEGV. Is this a bug?

http://lab.loman.net/2016/07/30/nanopore-r9-data-release/

Thanks in advance, Tomohiro

**Comment by MuraseTomohiro** [comment]
Additional information of Debugging

The following message appeared.

```
NextGenMap-LR 0.1.6 (build: Nov 29 2016 16:41:27, start: 2016-12-13.16:46:53)
Contact: philipp.rescheneder@univie.ac.at
Wrinting output (SAM) to stdout
Encoding reference sequence.
Size of reference genome 4 Mbp (max. 68719 Mbp)
Allocating 2321828 (4707986) bytes for the reference.
BinRef length: 2321826ll (elapsed 0.017878)
0 reference sequences were skipped (length < 10).
Writing encoded reference to /home/mrs/data/E_coli/E_coli_ref.modify.fa-enc.2.ngm
Writing to disk took 0.00s
Building reference table
Allocated 1 hashtable units (tableLocMax=2^32.000000, genomeSize=2^22.146828)
Building RefTable #0 (kmer length: 13, reference skip: 2)
	Number of k-mers: 67108865
	Counting kmers took 0.15s
	Average number of positions per prefix: 1.044048
	0 prefixes are ignored due to the frequency cutoff (1000)
	Index size: 335544325 byte (67108865 x 5)
	Generating index took 0.35s
	Allocating and initializing prefix Table took 0.00s
	Number of prefix positions is 1547214 (4)
	Size of RefTable is 6188856
	Number of repetitive k-mers ignored: 0
	Overall time for creating RefTable: 0.65s
Writing RefTable to /home/mrs/data/E_coli/E_coli_ref.modify.fa-ht-13-2.2.ngm
Writing to disk took 0.30s
Input is Fasta
Mapping reads...
Could not decode reference for alignment
Could not align reference sequence for read a912a961-475a-4901-84e9-27046e9257bc_Basecall_Alignment_template.
Terminating
```

I checked the code and found the cause of error at function of DecodeRefSequenceExact  in SequenceProvider.cpp.

Thanks.

**Comment by philres** [comment]
Hi and thanks for the bug report!
I'll have a look at it and let you know as soon as it is resolved!

**Comment by philres** [comment]
Just a quick update. I was able to identify the problem and I am currently fixing it but it will take a day or two to run additional tests. 

I'll keep you posted.

**Comment by MuraseTomohiro** [comment]
Hi phillres,

Thank you for update.
I'll check it.

Thanks,

Tomohiro

**Comment by philres** [comment]
Hi again and sorry for the late reply! 
I wanted to add a few other improvements before a new release and that took longer than expected.
Finally, I just uploaded a new version of ngmlr (v0.2.1). Could you please download it and check whether it solved your problem?

Thanks, 
Philipp
