### ISSUE TITLE
NGM-LR output format - SAM/BAM tags

### ISSUE THREAD

**Issue by mjjlou** [philres/ngmlr#33]
Hi Philipp,

What do the following tags means your output? I could not find documentation to tell me.

* KB
* SB
* ID
* QE
* XE
* XI
* XR
* AS
* QS
* XS
* CV
* SV

Thanks,
Melanie

**Comment by philres** [comment]
Hi Melanie,

thanks for you question. Please see https://github.com/philres/ngmlr/issues/15

Let me know if you have any other questions.

Best,
Philipp
