### ISSUE TITLE
Recommended parameters for detecting inversions

### ISSUE THREAD

**Issue by ylipacbio** [philres/ngmlr#37]
Hi Philipp,

I am wondering is there a recommended parameters to detect inversions ranging from 50 (or 100) to 10000 base pairs?

I noticed that NGMLR may detect inversions correctly, but also may force align 100bp inversions with lots mismatches for pacbio reads with the following parameters: 

```--max-segments 3 -R 0.01 -x pacbio```

<img width="703" alt="screen shot 2018-02-21 at 10 31 46 am" src="https://user-images.githubusercontent.com/3189673/36498214-77efbba8-16f2-11e8-9d05-c9bd8ea6458d.png">

For example, this NGMLR alignments on alignments with a 100bp inversion. NGMLR detected inversions on some of the reads accurately, and force aligned the others with mismatches.

I am wondering if there is a better set of parameters that I could try. 

Thank you very much!

Sincerely,
Yuan

**Comment by fritzsedlazeck** [comment]
Hey Yuan,
I am sure Philipp will respond soon. All I can think of is to try to reduce the --subread-length , which by default is set to 256. 
Cheers
Fritz
