### ISSUE TITLE
mapped and unmapped reads

### ISSUE THREAD

**Issue by mictadlo** [philres/ngmlr#39]
Hi,
Is there a way to produce as output mapped and unmapped reads or is there is another way to distinguish them in ngmlr?

Thank you in advance.

Best wishes,

Michal

**Comment by fritzsedlazeck** [comment]
You can obtain the not mapped reads via samtools view.  I think it is samtools view -f 4 your.sam > your-unmapped.sam

Picard has a webpage to look at the filter options from the tags per read (-f parameter) .
Cheers
Fritz
