### ISSUE TITLE
log with: corrupted unsorted chunks

### ISSUE THREAD

**Issue by KamilSJaron** [philres/ngmlr#4]
Hello, I run NextGenMap-LR v0.1.5 (build: Oct  6 2016 14:38:17, start: 2016-12-15.10:49:41) on Linux cluster - mapping two PacBio libraries to reference (rather crappy reference - a lot of scaffolds):

```bash
ngmlr -t 31 -r reference.fa -q filtered_subreads.fastq.gz | samtools view -bS - | samtools sort - > map.bam
```
one job finished ok, but the second job have produced an unexpectedly small `bam` file, a 20G big binary file called `core.12760` and the log in the end of this issue. I previously mapped this library to different reference and it worked (with the very same script I believe). There were fewer reads in the library that failed, therefore I would not guess that it will be a problem of resources.

```
ESC[AESC[2KProcessed: 310232 (152.90 r/s), Time: 4.00 1.00 68.08, Align ratio: 0.98, Corridor: 381
Alignmentlength (136) < exactAlingmentlength (179)
*** Error in `ngmlr': free(): corrupted unsorted chunks: 0x00002b1481690e70 ***
======= Backtrace: =========
[0x5499f1]
...
[0x59d109]
======= Memory map: ========
00400000-0067c000 r-xp 00000000 00:19 1476424450                         /Home/kjaron/bin/ngmlr
0087c000-00886000 rw-p 0027c000 00:19 1476424450                         /Home/kjaron/bin/ngmlr
00886000-00890000 rw-p 00000000 00:00 0 
01a1c000-03ace000 rw-p 00000000 00:00 0                                  [heap]
2b11dac49000-2b11ffaa5000 rw-p 00000000 00:00 0 
...
2b179f503000-2b17f7aff000 rw-p 00000000 00:00 0 
7fff6a319000-7fff6a32f000 rw-p 00000000 00:00 0                          [stack]
7fff6a3b7000-7fff6a3b8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
[bam_sort_core] merging from 24 files...
```

**Comment by philres** [comment]
Hi and thanks for the report!

We are working on a new version of ngmlr that should resolve several issues with smaller and/or fragmented reference genomes. I'll let you know as soon as it is finished (it should be ready early next week). Would be great if you could try run it on your data. 

Best,
Philipp

**Comment by RuiMMFaria** [comment]
Dear Phillipp,

I have been facing the same error supported above. You seem to suggest that cause is that the reference genome, which is very fragmented. In my case it makes sense, as I'm trying to map reads from a fastqc file of 141GB into a reference with 380.000 contigs. Do you already have the new version for fragmented genomes available for testing?

Many thanks,

Rui

**Comment by philres** [comment]
Hi Rui!

Sorry for the late reply, the new version is now ready!
Would be great if you could try it. 
380.000 contigs is really a lot and I don't have data at the moment to make a suitable test case for this. So if it still doesn't work, please let me know and I'll look into again. 

Thanks,
Philipp

**Comment by RuiMMFaria** [comment]
Thanks Philipp!

I would like to give it try. I can start next week and let you know.
Cheers,

Rui

**Comment by philres** [comment]
Great, thank you!
