### ISSUE TITLE
rel3 nanopore wgs workflow

### ISSUE THREAD

**Issue by ramcn** [philres/ngmlr#45]
Hello,

I am using ngmlr to generate the equivalent of NA12878 dataset "NA12878/ont/ngm_Nanopore_human_ngmlr-0.2.3_mapped.bam" used in the manuscript.

I downloaded the rel3-nanopore-wgs-152889212-FAB45271.fastq.gz from nanopore WGS dataset and used the below command.

1.  ngmlr --match 3 --mismatch -7 --gap-decay 0.1 -t 15 -r hs37d5.fa -q rel3-nanopore-wgs-152889212-FAB45271.fastq.gz -o output.sam
2. samtools view -S -b output.sam  > output.bam 

But the output.bam file I am getting is no way close to the size of ngm_Nanopore_human_ngmlr-0.2.3_mapped.bam which is about 110G.

Could you please let me know what I am missing in the workflow. Should I merge all the rel3 fastq files before running the ngmlr command?

Thank you,
Ram

**Comment by philres** [comment]
Hi,

Unfortunately, the nanopore-wgs website is a bit misleading. The download command on the front page is only an example and rel3-nanopore-wgs-152889212-FAB45271.fastq.gz is the data from only one of the flow cells. In total the Nanopore WGS consortium sequenced 39 flowcells for rel3 and another ~14 in rel4 (ultra-long reads). We used all of them, therefore our BAM file is much larger than yours.

In any case I would strongly recommend to use the rel5 data from here: https://s3.amazonaws.com/nanopore-human-wgs/rel5-guppy-0.3.0-chunk10k.fastq.gz

Rel5 contains all the data from rel3 and rel4 but basecalled with a more recent basecaller which improves SV calling results significantly!

The rel5 link above is a concatenated FASTQ file which means that you only have to download and map this one file.

Hope that helped,
Philipp

**Comment by ramcn** [comment]
Got it! I am able to proceed forward using rel5 data.  Thanks a lot for the quick response Philipp. 

Cheers,
Ram
