### ISSUE TITLE
make fail : /usr/bin/ld: attempted static link of dynamic object `/usr/local/lib/libz.so'

### ISSUE THREAD

**Issue by gn01786955** [philres/ngmlr#5]
my error message is 
```
[ 96%] Building CXX object src/CMakeFiles/ngmlr.dir/unix.cpp.o
[100%] Building CXX object src/CMakeFiles/ngmlr.dir/unix_threads.cpp.o
Linking CXX executable ../../bin/ngmlr-0.1.6/ngmlr
/usr/bin/ld: attempted static link of dynamic object `/usr/local/lib/libz.so'
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/ngmlr-0.1.6/ngmlr] Error 1
make[1]: *** [src/CMakeFiles/ngmlr.dir/all] Error 2
make: *** [all] Error 2
```
```
$ ls -l /usr/local/lib/libz.so*
 libz.so -> libz.so.1.2.8
 libz.so.1 -> libz.so.1.2.8
 libz.so.1.2.8
```

Link path of my ZLIB
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.8")

my system is ubuntu 14.10

I have reinstalled the zlib-1.2.8, But I had the same questions
How can I find a solution to this problem
Thank you for your help

**Comment by philres** [comment]
Hi,

to install everything that is required to build ngmlr on ubuntu please do the following:

```bash
sudo apt-get install git wget gcc g++ libc6-dev make cmake zlib1g-dev
```

If you are familiar with docker you could alternatively use the docker image I'm using to build ngmlr on my Mac

```
docker pull philres/nextgenmaplr-buildenv
```
Just install docker and build ngmlr in this container.

Please let me know if this helped!

Thanks,
Philipp

**Comment by gn01786955** [comment]
@philres 
Thank you for your prompt reply
I executed with  sudo apt-get install git wget gcc g++ libc6-dev make cmake zlib1g-dev ,
and had the same problem .
I had installed docker and executed  with docker pull philres/nextgenmaplr-buildenv .
I don't know that how to build ngmlr on your Mac

1   pull philres/nextgenmaplr-buildenv
2   sudo docker run -t -i philres/nextgenmaplr-buildenv

may i ask you a question ，How do I get to the next step ?

**Comment by philres** [comment]
Hi! Sorry for the late reply!

The steps are:

```bash
git clone https://github.com/philres/nextgenmap-lr.git
mkdir -p nextgenmap-lr/build
docker run -v `pwd`/nextgenmap-lr:/nextgenmap-lr philres/nextgenmaplr-buildenv bash -c "cd /nextgenmap-lr/build && cmake .. &&  make"
`pwd`/nextgenmap-lr/bin/ngmlr-0.2.1/ngmlr
```
Depending on how you configured docker, you might need `sudo` for running the docker command.

Best,
Philipp

**Comment by philres** [comment]
Btw, if you just want to run ngmlr, it is now also available in (mini)conda (http://bioconda.github.io/recipes/ngmlr/README.html) and as docker image on https://quay.io/repository/philres/ngmlr
