### ISSUE TITLE
Only 14.03% reads mapped

### ISSUE THREAD

**Issue by WeichenZhou** [philres/ngmlr#50]
Hi,
As I extracted (fastq-dump) a fastq file from .sra of the PacBio data, ngmlr aligned it to reference genome using default command line (ngmlr -t 6 -r hs37d5.fa -q SRR.fastq -o SRR.sam). The result turned out to be bad that only 14.03% reads in this fastq file mapped to reference according to the log file from ngmlr. (The fact is that all fastq files from this human sample like what I did previously have low mapped reads ratio.)
I was wondering if I missed some important intermediate step, or is the fastq file by fastq-dump not good and I should use .h5 instead?
Thanks a lot!

Arthur

**Comment by fritzsedlazeck** [comment]
Hi Arthur,
were these pacbio or ONT data? 
Have you checked the length of these reads?
Maybe you can point us to the accession. 
Cheers
Fritz

**Comment by WeichenZhou** [comment]
Hi Fritz,
They are PacBio data. I just looked at the SRR.sam file. The RNAME, POS, CIGAR etc. fields show value of 0. I feel like there is something wrong with fastq file or my ngmlr command line....

Arthur

**Comment by fritzsedlazeck** [comment]
Frankly its probably the input. Which accession is it?

**Comment by WeichenZhou** [comment]
SRR2026754 is the accession. Thanks!

**Comment by WeichenZhou** [comment]
Yeah I feel like the fastq file from .sra is odd. As I used .h5 and ran blasr, the result seemed pretty reasonable.

**Comment by fritzsedlazeck** [comment]
Sorry I just remembered that I had a similar issue before. 
What happens is a bit strange: So when you download the fastq you get all the reads including these that fail the Pacbio thresholds. When you run blasr with the h5 files it thresholds reads and ignore a bunch. 

To check this you can check the number of mapped reads: e.g. samtools view -c -F4 your_bam.bam

Let me know if that is the case or not. 
Thanks
Fritz

**Comment by WeichenZhou** [comment]
Yeah, I just checked my output which does have mapped reads. I still feel wired, because the blasr output is much larger than ngmlr output (12G vs 1.4G, 131k lines vs 33k lines). I just concerned whether the fastq file misses some reads/information while .h5 does not... 
Thanks a lot for your quick reply.
Arthur

**Comment by fritzsedlazeck** [comment]
What does the samtools view -c -F4 your_mapped_file give you for both?

File sizes can be very misleading and lines two. Although it is true that there is a large difference. 

For NGMLR it ignores reads if a certain % of its length is not mapped. (-R parameter) 
Thanks for your help to debug this behavior.
Fritz

**Comment by fritzsedlazeck** [comment]
Sorry, yes that is what I mean that the fastq -> mapping and h5 -> blasr mapping results in different number of reads that pass an initial filter threshold. 


I would try to e.g. use picard tools to extract the reads from the blasr output (samtofastq) and run it with NGMLR. Sorry for the extra work and I really appreciate the reporting. 
thx
Fritz

**Comment by WeichenZhou** [comment]
Thanks a lot!

**Comment by ylipacbio** [comment]
Sorry to chim in this thread.
Just FYI @WeichenZhou, an alternative way to get fastq from PacBio h5 is:
1 - Use bax2bam to convert h5 to bam file
2 - Use bam2fastq to convert bam to fastq file

**Comment by WeichenZhou** [comment]
@ylipacbio Thanks a lot! :)
