### ISSUE TITLE
Do fastq per-base read qualities influence mapping?

### ISSUE THREAD

**Issue by wtwhite** [philres/ngmlr#56]
Hi,

Is the quality information present in fastq files used by `ngmlr` at all?  That is, if I convert a fastq file to a fasta file and give that to `ngmlr`'s `-r` option, can I be certain of getting the same resulting SAM file?  If so, this will save me some disk space, and also let me use Gene Myers's `dextract` tool to pull read data out of old .bax PacBio files for mapping with `ngmlr` (apparently the tool is fast, but can only extract fasta, not fastq).  I checked the `ngmlr` and `ngm` github pages and the latter's FAQ, and couldn't see any indication that per-base quality values affect mapping, but I'd like to be sure.

Thanks in advance!

**Comment by fritzsedlazeck** [comment]
Hi,
we are not using the base qualities. 
Cheers
Fritz

**Comment by wtwhite** [comment]
Thanks for the lightning-fast response!
