### ISSUE TITLE
failed when mapping pacbio data to reference 

### ISSUE THREAD

**Issue by xthua** [philres/ngmlr#6]
hi, when I try to map pacbio data to reference via NextGenMap-LR 0.1.6 (build: Nov 29 2016 16:41:27, start: 2016-12-26.22:31:35), the program was Terminating.
command line: /data/xthua/tools/nextgenmap-lr/ngmlr-0.1.6/ngmlr -t 128 -r ../XH317.fa -q ../../../XH988-XH317/Analysis_Results/combined.fa -o ng.sam 
The error information was listed below:
Could not decode reference for alignment
Could not align reference sequence for read m161212_181230_42256_c101054842550000001823247601061741_s1_p0/127521/0_18785.
Thanks very much!

Best wishes,

Xiaoting

**Comment by wjidea** [comment]
Hi,

I got the same error while I was mapping fasta reads to the reference.

> ngmlr -r $REF -q $READ -o $OUT -t 20
> NextGenMap-LR 0.1.6 (build: Nov 29 2016 16:41:27, start: 2016-12-27.16:08:58)
> Contact: philipp.rescheneder@univie.ac.at
> Opening for output (SAM): /data/run/wangj/projects/05_Erwinia_genomics/structuralVar/mapping/249.sam
> Reading encoded reference from /data/run/wangj/projects/05_Erwinia_genomics/refGenome/ATCC49946.fna-enc.2.ngm
> Reading 3 Mbp from disk took 0.00s
> Reading RefTable from /data/run/wangj/projects/05_Erwinia_genomics/refGenome/ATCC49946.fna-ht-13-2.2.ngm
> Reading from disk took 0.26s
> Input is Fasta
> Mapping reads...
> Could not decode reference for alignment
> Could not align reference sequence for read m161022_170429_42146_c101102972550000001823260204261761_s1_p0/88005/24115_38554.
> Terminating

Thanks,

Jie

**Comment by wjidea** [comment]
@xthua I kind of solved this problem. I have merged all three fasta files into one combined fasta file. I guess the combined fasta file caused this problem. Now I just mapped each fasta file to reference separately, it worked just fine.

**Comment by philres** [comment]
Hi and thanks for the bug report!

I just uploaded ngmlr 0.2.1. Could you please try whether this update solved the problem?

If not, please let me know!

Thanks,
Philipp

**Comment by wjidea** [comment]
I am testing it on NextGenMap-LR 0.2.2 (build: Jan 15 2017 13:38:00, start: 2017-01-18.09:13:27), which was installed from bioconda.

**Comment by philres** [comment]
Thats perfectly fine as well. 0.2.2 should give the same results as 0.2.1 as it only adds conda compatibility.
