### ISSUE TITLE
depth according to bam

### ISSUE THREAD

**Issue by bluesea2017** [philres/ngmlr#7]
Hi,
  I use samtools or bamtools to caculate the depth according to bam ,but the average depth is  less  than 2 x,species:human,pacbio,raw data 60x. The problem : samtools is compatible bam ? What can I use to caculate depth ?

Thanks!

**Comment by philres** [comment]
Hi!

Could you please send me the exact command you are using to compute the read depth?

Best,
Philipp

**Comment by philres** [comment]
Hi again!

I'll consider this closed for now. Samtools depth works for my test samples.
If you still experience problems with this, don't hesitate to reopen it and please send me the exact command you used to for ngmlr and samtools.

Best,
Philipp
