### ISSUE TITLE
differences between ONT and PacBio data

### ISSUE THREAD

**Issue by Wuxy96** [philres/ngmlr#71]
Hi,

As you suggested when running Oxford Nanopore data should use parameter -x ont.
I wonder the differences between -x ont and -x pacbio, 
And the effect of Oxford Nanopore data with -x pacbio.

Thanks a lot

**Comment by fritzsedlazeck** [comment]
The differences are mainly scoring function and other parameters to account for a different sequencing error profile of the ont vs. pacbio reads. 
We did not recently benchmark the ont parameter on pacbio data. 
Thanks
Fritz

**Comment by Wuxy96** [comment]
Thanks for your reply,

How about the effect of  pacbio parameter on ONT data?

**Comment by fritzsedlazeck** [comment]
Same we did not benchmark this aspect since a while..
