### ISSUE TITLE
Tag NM in SAM

### ISSUE THREAD

**Issue by Wuxy96** [philres/ngmlr#72]
Hi,

I got the output of ngmlr, and I have a question about NM in SAM file.
does that mean the sum of insertion,deletion and mismatch of a alignment?
if CIGAR=23S19M1I15M1I12M1I30M1D17M1D50M63S, and NM=22, so the count of mismatch is 22-1-1-1-1-1=17?

Thanks

**Comment by fritzsedlazeck** [comment]
Exactly, but the CIGAR does not encode mismatches. M is for both matches and mismatches by definition. 

Thanks
Fritz
