### ISSUE TITLE
ngmlr version 0.2.8

### ISSUE THREAD

**Issue by Wuxy96** [philres/ngmlr#73]
Hi,

I downloaded ngmlr version 0.2.8 a few months ago, and I just can't find this version from releases.
Is v0.2.8 not in use? What are the differences between v0.2.8 and v0.2.7 about the mapping output? 
I have already run v0.2.8 with a lot of samples, so it will spend a lot of time rerunning with v0.2.7. 

Thanks a lot.

**Comment by fritzsedlazeck** [comment]
There is no need to rerun. 0.2.8 is fine. 
Thanks
Fritz

**Comment by Wuxy96** [comment]
Thanks for your reply.

**Comment by Wuxy96** [comment]
OK, thank you so much for you reply.
