### ISSUE TITLE
Read index

### ISSUE THREAD

**Issue by shimbalama** [philres/ngmlr#74]
Hi, I'm using NGMLR in WDL so I have to use --skip-write or it writes and index per shard (1000+). Is it possible to read an existing index in to save generating it for every shard?

Thanks,
Liam

**Comment by fritzsedlazeck** [comment]
You can run ngmlr with no sample only the reference once. This should store the index. Subsequently, just call ngmlr with the same reference and path and it should be fine. 

I hope that helps.
Cheers
Fritz

**Comment by niemasd** [comment]
This is useful information, and it may be worth mentioning in the README and/or in the usage message (I was wondering precisely this, looked through the README, didn't see any info about it, looked at the help message, didn't see anything there, and then hoped someone had asked about it in a GitHub Issue)

**Comment by niemasd** [comment]
Actually, I tried running NGMLR like this:

```bash
ngmlr -x pacbio -t 8 -r /home/niema/.viralmsa/NC_001802/NC_001802.fas
```

And while it did create the reference, it assumed reads would be passed in via STDIN so it just hung infinitely until force-closed. Same behavior when I just run with just the reference genome + number of threads:

```bash
ngmlr -t 8 -r /home/niema/.viralmsa/NC_001802/NC_001802.fas
```

A hacky workaround for now is to just pipe in nothing, but it would be nice if there were a better solution (I can't seem to find one):

```bash
echo -n "" | ngmlr -x pacbio -t 8 -r /home/niema/.viralmsa/NC_001802/NC_001802.fas
```
