### ISSUE TITLE
possible conflict of encoded reference file

### ISSUE THREAD

**Issue by zhixingfeng** [philres/ngmlr#77]
Hi Philipp,

I found that ngmlr generates encoded reference (.ngm) in the directory of the input reference file. If I align multiple read files at the same time using the same reference file (submit multiple jobs of ngmlr), is that possible that these processes would conflict with each other? For example, one process is trying to load the encoded reference but another process just overwrote it and only wrote half of the content to it.

I tried to run 29 ngmlr jobs using the same reference file at the same time, and 28 of them succeed but 1 of them gave me an error "Invalid encoded reference file found: ../ref/reference.fna-enc.2.ngm. Please delete it and run NGM again."  Is this error caused by the conflict of reference file I mentioned above? Thanks a lot.

Best

Zhixing

**Comment by fritzsedlazeck** [comment]
Dear Zhixing,
I am personally always careful with that. So I typically run only 1 instance of NGMLR to index the reference first (just specify the reference without a fastq). Once this is done you can safely run all the data sets at once. 
I hope that helps
Fritz

**Comment by zhixingfeng** [comment]
Hi Fritz,
Thank you so much for your help. That helps to get around this issue.  

Best

Zhixing
