### ISSUE TITLE
PacBio: ccs/hifi-reads or filtered subreads?

### ISSUE THREAD

**Issue by MrTomRod** [philres/ngmlr#88]
I have PacBio RS II raw data: `.bax.bam`-files. I created two kinds of `.fastq`-files from them:

- circular consensus sequences (ccs/HiFi) (created using: `pls2fasta in.bax.h5 out.fasta -trimByRegion -ccs`)
- filtered subreads (`filtered_subreads.fastq` created by HGAP)

Which one should I use for `ngmlr`?

(In case it's relevant: Afterwards, I want to use [Sniffles](https://github.com/fritzsedlazeck/Sniffles) to call structural variants.)

**Comment by fritzsedlazeck** [comment]
So you sequenced HiFi reads ? If that is the case you need the collapsed fastq . We typically use the ccs program directly. 

If its CLR Pacbio reads then the subreads.fastq

hope the clears this up.
Thanks
Fritz

**Comment by MrTomRod** [comment]
The command `pls2fasta in.bax.h5 out.fasta -trimByRegion -ccs` gave me an error: `ERROR, could not initialize file`, but without `-ccs` it works. I suppose that means it's not HiFi reads.

I'm sorry for bothering you, it's the first time I'm working with PacBio data and I've inherited data from an old experiment (2016) that was prepared by somebody who has now left the group. :sweat_smile:

**Comment by fritzsedlazeck** [comment]
No worries at all! 
you can map the raw reads also with NGMLR. It doesn't have to be HiFi reads. 
Thanks
Fritz
