### ISSUE TITLE
gcc version

### ISSUE THREAD

**Issue by chaijinchao** [philres/ngmlr#9]
Hi,

my gcc version is 4.4.6 , the direction is in /usr/bin/gcc.   ngmlr need gcc/g++ (>=4.8.2), and i installed gcc(4.9.1) in other direction.  when i run cmake,  it doesn't work as:
         
-- The C compiler identification is GNU 4.4.6
-- The CXX compiler identification is GNU 4.4.6
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.8") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
CMake Error at CMakeLists.txt:28 (message):
  The compiler /usr/bin/c++ has no C++11 support.  Please use a different C++
  compiler.
-- Configuring incomplete, errors occurred!
See also "/share/work1/staff/chaijc/software/ngmlr/build/CMakeFiles/CMakeOutput.log".
See also "/share/work1/staff/chaijc/software/ngmlr/build/CMakeFiles/CMakeError.log".

it seems to use the /usr/bin/gcc(4.46), but my bashrc is gcc(4.9.1). i want to know how to solve it?

**Comment by philres** [comment]
Hi,

You have to tell cmake where your gcc/g++ is located.

So instead of doing:
`cmake ..`
try:
`cmake -D CMAKE_C_COMPILER=<path to gcc> -D CMAKE_CXX_COMPILER=<path to g++> ../..`
for example:
`cmake -D CMAKE_C_COMPILER=/opt/bin/gcc-4.9 -D CMAKE_CXX_COMPILER=/opt/bin/g++-4.9 ../..`

Let me know if that helps.

Best,
Philipp

**Comment by chaijinchao** [comment]
it works as you said, thank you very much.
