### ISSUE TITLE
--bam-fix and cs tag

### ISSUE THREAD

**Issue by sjin09** [philres/ngmlr#91]
Hello @philres 

The --bam-fix option didn't produce the cs tag like the one from minimap2. I am hoping to compare the alignment results and mutation calling results from two aligners and I was wondering if I was doing something wrong with regards to the alignment parameters or if ngmlr no longer produces the cs tag.

My command was the following:

```
ngmlr --rg-sm "$SAMPLE" --rg-lb "CCS" --rg-pl "PACBIO" --rg-pu "$SMRTcell" -r ${REFERENCE} --bam-fix -x pacbio -t 10 -q $SAMPLE.ccs.fastq.gz | samtools view -hb - > ${OUT_PATH}/$1/hg19.$SAMPLE.ngmlr.bam 
```

Many thanks,
Sangjin

**Comment by fritzsedlazeck** [comment]
Dear @sjin09 ,
the cs tag is not a standard tag from the sam format. It is something that Minimap2 introduced. Thus, we will not integrate this. 
The MD and Cigar string indicates how the pairwise alignment will look like and the NM tag gives the edit distnace. 
I hope that helps
Cheers
Fritz

**Comment by sjin09** [comment]
Thanks @fritzsedlazeck.

I was confused as the release said "--bam-fix writes CS tag (Thanks Heng)" I will re-create the CS tag from cigar string and MD tag.
